export * from './pokemon-db'
export * from './type-db'
export * from './ability-db'
export * from './origin-type-db'
export * from './origin-ability-db'
export * from './damage-relation-db'
export * from './movement-db'
