export * from './pokemon/pokemon-impl.repository'
export * from './pokemon/pokemon.repository'
export * from './type/type-impl.repository'
export * from './type/type.repository'
export * from './ability/ability-impl.repository'
export * from './ability/ability.repository'
export * from './movement/movement-impl.repository'
export * from './movement/movement.repository'
